-- 1. FORCE CLEANUP
-- We drop the child tables first, then the parent tables.
DROP TABLE IF EXISTS public."UserModule_Rights" CASCADE;
DROP TABLE IF EXISTS public.user_module CASCADE;
DROP TABLE IF EXISTS public.rights CASCADE;
DROP TABLE IF EXISTS public."Module" CASCADE;

-- 2. CREATE TABLES WITH PUBLIC SCHEMA
-- Using "Module" with double quotes to ensure it matches your PR requirements exactly.
CREATE TABLE public."Module" (
    module_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    module_name VARCHAR(50) UNIQUE NOT NULL
);

CREATE TABLE public.rights (
    right_id INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    right_code VARCHAR(50) UNIQUE NOT NULL,
    description TEXT
);

CREATE TABLE public.user_module (
    user_id UUID NOT NULL, 
    module_id INT REFERENCES public."Module"(module_id),
    PRIMARY KEY (user_id, module_id)
);

CREATE TABLE public."UserModule_Rights" (
    user_id UUID NOT NULL,
    module_id INT NOT NULL,
    right_id INT REFERENCES public.rights(right_id),
    is_enabled SMALLINT DEFAULT 1,
    PRIMARY KEY (user_id, module_id, right_id),
    FOREIGN KEY (user_id, module_id) REFERENCES public.user_module(user_id, module_id)
);

-- 3. SEED DATA (Execute only after tables are created)
INSERT INTO public."Module" (module_name) VALUES 
('Cust_Mod'), ('Sales_Mod'), ('Prod_Mod'), ('Adm_Mod');

INSERT INTO public.rights (right_code, description) VALUES 
('CUST_VIEW', 'View Customer records'),
('CUST_ADD', 'Add new Customers'),
('CUST_EDIT', 'Edit Customer details'),
('CUST_DEL', 'Soft delete Customers'),
('SALES_VIEW', 'View Sales records'),
('SD_VIEW', 'View Sales Detail records'),
('PROD_VIEW', 'View Product list'),
('PRICE_VIEW', 'View Pricing History'),
('ADM_USER', 'System Administration');